services:
    neo4j: 
        image: neo4j:4.4-community
        container_name: neo4j_graph
        ports:
            - "7474:7474"  # HTTP-порт для браузера Neo4j
            - "7687:7687"  # Bolt-порт для Cypher-клієнтів
        volumes:
            - ./neo4j/data:/data
            - ./neo4j/logs:/logs
        environment:
            - NEO4J_AUTH=neo4j/UIOP1234
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
volumes:
    neo4j:
        driver: local
