version: "3.2"

services:
  consul:
    container_name: 'consul-server'
    image: 'hashicorp/consul'
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -ui -node=consul-server 
      -bootstrap-expect=1 -client=0.0.0.0


  hazelcast-node1:
    container_name: 'hazelcast-node1'
    image: 'hazelcast/hazelcast:5.4.0'
    environment:
      - HZ_CLUSTERNAME=distributed-consul-cluster
      - HZ_NETWORK_PUBLICADDRESS=192.168.88.164:5701
    ports:
      - '5701:5701'
    networks:
      - hazelcast-network

  hazelcast-node2:
    container_name: 'hazelcast-node2'
    image: 'hazelcast/hazelcast:5.4.0'
    environment:
      - HZ_CLUSTERNAME=distributed-consul-cluster
      - HZ_NETWORK_PUBLICADDRESS=192.168.88.164:5702
    ports:
      - '5702:5701'
    networks:
      - hazelcast-network

  hazelcast-node3:
    container_name: 'hazelcast-node3'
    image: 'hazelcast/hazelcast:5.4.0'
    environment:
      - HZ_CLUSTERNAME=distributed-consul-cluster
      - HZ_NETWORK_PUBLICADDRESS=192.168.88.164:5703
    ports:
      - '5703:5701'
    networks:
      - hazelcast-network


  hazelcast-management:
    container_name: 'hazelcast-management-center'
    image: 'hazelcast/management-center:5.4.0'
    depends_on:
      - hazelcast-node1
      - hazelcast-node2
      - hazelcast-node3
    ports:
      - '8008:8080'
    networks:
      - hazelcast-network


networks:
  hazelcast-network:
    driver: bridge
